#!/bin/bash

name=$(./jq.exe -r '.name' data.json | sed 's/.*/\u&/')
height=$(./jq.exe '.height' data.json | awk '{ printf "%.1f", $1 / 10 }')
weight=$(./jq.exe '.weight' data.json | awk '{ printf "%.0f", $1 / 10 }')
type=$(./jq.exe -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."
